### ISSUE TITLE
docker-compose -f php71_nginx_mysql_full_ce.yml run composer install 

### ISSUE THREAD

**Issue by rvpalivoda** [oroinc/environment#13]
$ docker-compose -f php71_nginx_mysql_full_ce.yml run composer install
Problem 1
     - Installation request for oro / platform 2.6.30 -> satisfiable by oro / platform [2.6.30].
     - oro / platform 2.6.30 requires ext-gd * -> the requested PHP extension gd is missing from your system.

**Comment by anyt** [comment]
GD extension actually not needed for composer container. It's required for php, cron and consumer containers only. 
That's why we install vendors inside composer container with flag to ignore this requirement.
 
run `docker-compose -f php71_nginx_mysql_full_ce.yml run composer install --prefer-dist --no-suggest --no-interaction --ignore-platform-reqs --optimize-autoloader` instead.
