### ISSUE TITLE
Community installation never end

### ISSUE THREAD

**Issue by AdriwanKenoby** [oroinc/environment#3]
I follow the instruction to setup an oro application but the installation process loop on that message `mail_1       | [APIv1] KEEPALIVE /api/v1/events` and never end.

I don't know how to debug this, i am using Docker version 18.03.0-ce, build 0520e24

**Comment by AdriwanKenoby** [comment]
Once installed I don't understand which port are exposed.

How can I connect to the web installer ? using my ip seems to not work

**Comment by AdriwanKenoby** [comment]
I am not on my localhost. Can i use it for production on remote server ?

**Comment by dxops** [comment]
`A Dockerized development environment for applications based on OroPlatform.`

> Can i use it for production on remote server ?

It's not optimized for production usage, QA and development only. The most critical items for production usage are:
- resource limits, unlimited right now, because of dev mode
- sources mounted into containers, it's better to build a container with sources inside

> Should I use the docker host as reverse-proxy ?

Yes, you can, just proxy everything from docker host to docker containers
